name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml
      working-directory: back

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug project structure
      
        run: |
          echo "Structure du projet :"
          ls -R
          echo "Contenu du dossier front :"
          ls -la front/
      
      - name: Setup Node.js for Angular 14
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      
      - name: Install dependencies
        run: npm ci --no-audit
        working-directory: front
        env:
          CI: true  # Force le mode CI pour npm
      
      - name: Verify Angular installation
        run: npx ng version
        working-directory: front
      
      - name: Run Angular tests with coverage
        run: |
          npm run test -- \
            --no-watch \
            --code-coverage \
            --browsers=ChromeHeadless \
            --progress=false
        working-directory: front
      
      - name: Verify coverage report exists
        run: |
          echo "Contenu du dossier coverage :"
          ls -la coverage/
        working-directory: front
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage/
          retention-days: 5