name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml
      working-directory: back

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js for Angular 14
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        working-directory: front  # Changé de frontend à front
        
      - name: Run Angular tests with coverage
        run: |
          npm run test -- --no-watch --code-coverage --browsers=ChromeHeadless
        working-directory: front  # Changé ici aussi
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage  # Nom modifié pour cohérence
          path: front/coverage/  # Chemin corrigé