name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build and test with Maven
      run: mvn -B package jacoco:report --file pom.xml
      working-directory: back

    - name: Verify Jacoco report exists
      run: |
        echo "Contenu du dossier target/site/jacoco :"
        ls -la target/site/jacoco/
      working-directory: back

    - name: Upload Jacoco report
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: back/target/site/jacoco/
        retention-days: 5

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug project structure
        run: |
          echo "Structure du projet :"
          ls -R
          echo "Contenu du dossier front :"
          ls -la front/
      
      - name: Setup Node.js for Angular 14
        uses: actions/setup-node@v4
        with:
          node-version: '16.20.2'
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      
      - name: Install dependencies
        run: npm ci --no-audit
        working-directory: front
        env:
          CI: true
      
      - name: Verify Angular installation
        run: npx ng version
        working-directory: front
      
      - name: Run Angular tests with coverage
        run: |
          npm run test -- \
            --no-watch \
            --code-coverage \
            --browsers=ChromeHeadlessCI \
            --progress=false
        working-directory: front
      
      - name: Verify coverage report exists
        run: |
          echo "Contenu du dossier coverage :"
          ls -la coverage/
          echo "Contenu du dossier bobapp :"
          ls -la coverage/bobapp/
        working-directory: front

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage/bobapp/
          retention-days: 5

  deploy-coverage:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Prepare coverage site
        run: |
          mkdir -p public
          # Backend
          mv artifacts/backend-coverage public/backend
          # Frontend
          mv artifacts/front-coverage public/front
          
          # Create index.html
          echo "<!DOCTYPE html>
          <html>
          <head>
              <title>Coverage Reports</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  h1 { color: #333; }
                  ul { list-style-type: none; padding: 0; }
                  li { margin: 10px 0; }
                  a { 
                      display: inline-block;
                      padding: 10px 15px;
                      background: #0366d6;
                      color: white;
                      text-decoration: none;
                      border-radius: 4px;
                  }
                  a:hover { background: #0356b6; }
              </style>
          </head>
          <body>
              <h1>Coverage Reports</h1>
              <ul>
                  <li><a href='backend/index.html'>Backend Report (Jacoco)</a></li>
                  <li><a href='front/index.html'>Frontend Report (LCOV)</a></li>
              </ul>
              <p>Generated on: $(date)</p>
          </body>
          </html>" > public/index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_branch: gh-pages
          # force_orphan: true