name: SonarCloud Backend Analysis

on:
  push:
    branches: [ main, master ]
    paths:
      - 'back/**'  # Ne s'exécute que lorsque des fichiers dans le dossier 'back' sont modifiés
  pull_request:
    branches: [ main, master ]
    paths:
      - 'back/**'
  workflow_dispatch:  # Permet de lancer l'analyse manuellement

jobs:
  sonarcloud-backend:
    name: SonarCloud Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important pour SonarCloud pour voir l'historique des commits
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and analyze
        working-directory: ./back  # Change to your backend directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_BOBAPP }}
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=silenusdev_bobapp-back \
          -Dsonar.organization=silenusdev \
          -Dsonar.host.url=https://sonarcloud.io